zenoamaro/react-quill

- src/component.js
The propType was wrongly set to 'object' and it generated warnings in the console while working perfectly fine :)
cheery, Andy
> changed propType of 'toolbar' to Array

- src/toolbar.js
Currently, it's not possible to add custom labels to the toolbar items. This pull request lets you specify `children` as a property for each item which gets passed as the children argument to `React.DOM.span`. In our case, we need to use our own icons from an `<Icon />` component.
> Adding ability to specify children prop for custom toolbar item labels

- README.md
- src/component.js
This PR adds two methods on ReactQuill nodes providing a simple imperative API over focusing:
- `focus()`: Focuses the editor.
- `blur()`: Removes focus from the editor.
To be able to call them, first [take a ref] to the editor, then invoke them on that ref:
~~~jsx
render() {
return (
<ReactQuill … ref="editor"/>
);
}
componentDidMount() {
this.refs.editor.focus();
}
~~~
Note that the ref will only be available while the component is mounted.
[take a ref]: https://facebook.github.io/react/docs/more-about-refs.html
> Add focus/blur methods on the editor node. Fixes #25.

- src/toolbar.js
The choices in the toolbar are missing the hover tooltips. The change is fixing this issue.
> add tooltips for the choices in toolbar

- src/index.js
There is no way to access Quill directly, and having this possibility allows for unlimited modifications/adding modules to editor. react-quill API doesn't allow to ex. create new module, and this can be a solution (for now at least).
```
var ReactQuill = require('react-quill');
ReactQuill.Quill.registerModule('my-image-tooltip', function (quill, options) {
// ...
});
```
> Exposed Quill

- src/component.js
Just a quick fix before proper fix later to enable image-tooltip by default. As of 0.3.0 we can't do anything to add image-tooltip (not the icon, it's doable via editing toolbar items).
> Adding image-tooltip to modules.

- src/toolbar.js
The current renderChoices raises warning:
> Warning: Use the `defaultValue` or `value` props on \<select\> instead of setting `selected` on \<option\>.
It can be seen in Console of "https://zenoamaro.github.io/react-quill/".
This commit solved the issue with not very elegant code. If it's OK to change the format of toolbar ```defaultItems``` a little bit (add "defaultValue" attribute to indicate selected item, instead of "selected:true"), the code could be simpler.
> Fix renderChoices of toolbar

- src/mixin.js
"oldDelta" and "oldRange" was  passed as "source" for onEditorChange and onEditorChangeSelection.
text-change: https://github.com/quilljs/quill/blob/master/core/editor.js#L221
selection-change: https://github.com/quilljs/quill/blob/master/core/selection.js#L274
Ignore oldDelta and oldRange?
> source is the third parameter

- src/index.js
Hey friends,
I may be misunderstanding what's going on, but I would expect that `Quill` should be included in the exports so that those using the library can customize parchment blots and things like that.
Perhaps it's expected that `Quill` is accessible via a global like `window.Quill`, but, IMHO, that shouldn't be assumed.
> Expose Quill in exports

- README.md
- src/component.js
- test/index.js
This will make ReactQuill be stricter in what it accepts as children.
Previously, a toolbar and an editor area would be accepted as children, distinguished by string ref, and hooked to the Quill instance.
Now, ReactQuill will only accept a single React element as a child, which will be directly connected to the editor without ref mangling. This area cannot be a `<textarea>`, something which the user is also warned of.
In theory, this would allow getting rid of the outer wrapper. In practice, however, I think it's useful enough to be worth keeping.
- User is warned about improper usage
- No more lookup by ref, which was a hack
- Parent refs are also maintained now, because we use function refs
- Anybody relying on the ability to provide arbitrary children to ReactQuill will not be able to …
> Strict rules for custom editing areas

- .jshintrc
- CHANGELOG.md
- README.md
- package.json
- src/component.js
Concept of `cleanProps` allows performing regular updates that affect DOM nodes.
Keyed elements and controlled lifecycle avoid breaking Quill when re-rendering.
Optimized comparisons for value prop updates after content changes.
Should fix #147 and others.
> Cleaner rerendering

- README.md
It seems like `node_modules/react-quill/dist/quill.base.css` got renamed to `quill.core.css` somewhere along the line and the `README.md` wasn't updated.
Thanks for the hard work `react-quill` team!
> update README.md to reference core.css instead of base.css

- package.json
Without this change, when `react-quill` is installed in a project which uses React 15.x, it would install its own React 0.14, nested in `myproject/node_modules/react-quill/node_modules/react`.
With my PR, `react-quill` uses the version of React already installed. It saved me a few KB.
> Update react peerDependency

- README.md
- demo/index.js
- src/component.js
- src/mixin.js
- test/index.js
This makes ReactQuill accept Deltas, in addition to HTML strings, for `value` and `defaultValue`.
Deltas are applied via `setContents()`, which means that plain objects are also supported. There is no official support for `updateContents()`, as it is imperative and destructive.
Deltas are kept around as the internal value whenever the `value` prop is also a Delta. Otherwise the HTML string is used, as was before. This might have some performance repercussions due to comparing objects instead of strings during update checks.
Notably, the `delta` object provided by the `onChange` event _must not_ be used as `value`. Because it does only provide a changeset, rather than a full document, it will easily trigger an update loop. I see this mistake to be as likely as it is dangerous, so …
> First-class support for Deltas. Closes #101

- README.md
- src/component.js
Adds a `tabIndex` property that is set on the editing area.
It affects both the built-in area and custom-provided one. Maybe it shouldn't affect both. This might be a point of contention. It does not provide anything for the toolbar at the moment.
It should be a minor bump.
> Added tabIndex prop for built-in editing area. Closes #232

- README.md
- demo/index.js
- src/component.js
Adds `onFocus` and `onBlur` event handlers, as shorthands derived from `onChangeSelection`.
They provide the new range, and the previous range, respectively, along with the usual `source` and `editor` arguments.
Should be just a minor bump.
> Adds focus and blur events. Closes #110

- demo/index.html
- demo/prop-types.js
- package.json
- src/component.js
- src/toolbar.js
- test/index.js
- webpack.dev.js
- webpack.prod.js
- yarn.lock
- add prop-types, react-dom-factories, create-react-class
- bump minimim React version to match required peer for above
- add external prop-types pkg to demo
Closes #238
Closes #241
Closes #235
Closes #191
Part of #181
cc @mikecousins I rebased your PR #242 on master and cleaned up the commit log
> Update dependencies to support React 16

- package.json
- types.d.ts
- yarn.lock
Fulfilling #269 This PR adds TypeScript type definitions to this project. These definitions build on top of the existing `@types/react` and `@types/quill` packages.
I've added definitions for:
- Mixin
- Component
- Toolbar
The dependancy versions of those are set to `*` so that they'll match whatever version that the user of this project has installed.
---
Closes #269
> Add TypeScript type definitions

- package.json
Love having the `.d.ts` file, but noticed is wasn't in the latest npm package.
> Add types.d.ts to the produced package.

- types.d.ts
Some minor fixes;
- `DeltaStatic` is undefined; `Quill.DeltaStatic` is most likely what was intended
- the `void`s fix the noImplicitAny directive
> Fix minor issues with types.d.ts

- types.d.ts
The previous code declared the toolbar property of the Modules interface to be deprecated, but according to the documentation it is not. I have added typings for the formats and a type for the toolbar property.
I have not tested the Modules.toolbar typing to it's limits so maybe someone else may find something I missed.
> Modules toolbar typings

- src/mixin.js
in `setEditorContents`. Prevents component from stealing focus if content changes when the editor isn't focused
Doesn't look like the current test suite covers focus behavior in any way, but the existing tests pass with these changes
> Only restore selection if editor has focus

- src/mixin.js
`dangerouslyPasteHTML` will always grab editor focus, which is not necessarily desired all the time. This simply moves up the logic without the focus part.
> Fix issue with unnecessary editor focus on mount

- types.d.ts
The `ReactQuill` is [assigned to](https://github.com/zenoamaro/react-quill/blob/master/src/index.js#L7) `module.exports`. So in types file, `ReactQuill` should not be exported as default. It should change to
```diff
- export default class Component extends React.Component<ComponentProps> {
+declare class ReactQuill extends React.Component<ReactQuill.ComponentProps> {
+export = ReactQuill;
```
See the [typescript issue](https://github.com/Microsoft/TypeScript/issues/8335#issuecomment-215194561) for detail.
> Change types to top level export

- src/component.js
> Expose config option scrollingContainer through ReactQuill props

- README.md
Hi 👋
Thanks for this wrapper around Quill! I wanted to add an example of how to make the unprivileged editor because it didn't seem obvious to me at all how you do that (particularly got tripped up on not realizing I needed to pass the editor to the makeUnprivilegedEditor() fn).
Hope this help!
> (docs) Add makeUnprivilegedEditor example to README

- src/component.js
- src/mixin.js
Until now the `tabIndex` isn't being propagated to the editor's scroll dom node (which is typically a `<div>` with `contenteditable="true"` and can thus be focused via keyboard tabbing). With this change we're propagating the tabindex to said dom node to establish a working tabindex for the editor.
Note: Quill unfortunately doesn't provide an API to set the editor's tabindex, so we have to override it directly on its dom node. Not sure if there's a better place to do it.
Also see https://github.com/zenoamaro/react-quill/issues/232#issuecomment-369199337
> Propagate tabindex prop to editor's scroll container

- types.d.ts
This is a fix for https://github.com/zenoamaro/react-quill/issues/361.
The problem is that when trying to import Quill from 'react-quill' in Typescript, it complains that react-quill has no exported member named Quill. Looking at the typings file, this is true. This fix adds Quill as an exported member to the typings file.
> Add Quill as an exported object to typings file

- types.d.ts
fix(types.d.ts): add key `scrollingContainer` to provide typing for feature added in https://github.com/zenoamaro/react-quill/pull/365
> add key `scrollingContainer` to provide typing

- src/mixin.js
Closes #381 
`editor-change`'s selection change seems to more completely cover the cases in which one expects `onChangeSelection` to be called.
Another idea was exposing `onEditorChange` as a prop, and although this might provide better backwards compatibility, it also seems more confusing.
I'm curious to hear whether my proposed approach seems valid, or if you perhaps expect it to break other parts of the wrapper.
> Use editor-change event to call onChange and onChangeSelection properties

- types.d.ts
Adds the preserveWhitespace prop in the TypeScript type definition program, since it was not added in #407
> Add preserveWhitespace prop in TS type definition

- src/index.tsx
Fixes #495 
It seems that in aa9759742f24f49bc651b1d65fd0e08b4f349d62 this if statement is actually needed. If setSelection is called with `null` then quill explicitly removes focus from *any* element on the screen. So in my usecase typing in another element becomes unfocused after each keystroke due to this.
/cc @jwngr
> Various fixes for beta

- README.md
The migration link in the readme has a typo, this change just fixes that
> Fix migration anchor link

- src/index.tsx
Fix bug mentioned [here](https://github.com/zenoamaro/react-quill/issues/784#issuecomment-1166342710) and introduced in #793.
> Fix events not firing in strict mode
